encoding: UTF-8
timezone: Europe/Bucharest
url: htpp://andibede.github.io

# site
title: NMR diffusometry and relaxometry laboratory
subTitle: site.subtitle
description:  site.description

# author
email: email.host
author: author

# markdown
markdown: kramdown
permalink: pretty


# social links
social:
  - title: facebook
    url: https://www.facebook.com/blank
  - title: github
    url: https://github.com/blank
  - title: linkedin
    url: https://ro.linkedin.com/blank
  - title: google-plus
    url: https://plus.google.com/blank

# simple form token
simpleform_token: blank
