encoding: UTF-8
timezone: Europe/Bucharest
url: htpp://andibede.github.io/

# site
title: NMR diffusometry and relaxometry laboratory
subTitle: site.subtitle
description:  site.description
year: 2015

# author
email: email.host
author: author

# markdown
markdown: kramdown
permalink: pretty

#gems
gems:
  - jekyll-sitemap

# simple form token
simpleform_token: blank

# google analytics
google_analytics_id: blank
